services:
  - type: web
    name: botfactory-ai
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT main:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SESSION_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: botfactory-db
          property: connectionString
      - key: GOOGLE_API_KEY
        sync: false
      - key: TELEGRAM_BOT_TOKEN  
        sync: false

databases:
  - name: botfactory-db
    databaseName: botfactory
    user: botfactory_user